### ISSUE TITLE
Only load .yml files in /menu/ directory (exclude .yml~)

### ISSUE THREAD

**Issue by OwnageTechGeek** [Derkades/ServerSelectorX#27]
When loading the menu files, ServerSelectorX loads all .yml files including .yml~.  Solution is to load all .yml files excluding any ending with .yml~ which  is an extension used while editing files on many Linux based text editors.

You said you'd open an issue, I noticed you haven't done it, so I did it myself.

**Comment by Derkades** [comment]
Oh yeah I forgot 😛

**Comment by Derkades** [comment]
The code currently also loads all files that do not end in .yml, (.foo) which I will fix as well
