### ISSUE TITLE
Error when compiling with Maven

### ISSUE THREAD

**Issue by MrFrozenSlushy** [Derkades/ServerSelectorX#31]
I get this error when trying to compile with Maven:

https://pastebin.com/nCaPG3ih

**Comment by Derkades** [comment]
My maven repo is currently down and will be for a few weeks. For now you need to clone https://github.com/Derkades/Derkutils/ and run maven install. Afterwards you should be able to compile ServerSelectorX.

Also keep in mind that the current code does not work, I have made some changes to the config file but not yet in the code.

**Comment by MrFrozenSlushy** [comment]
Ok sounds good
